### ISSUE TITLE
pdf to jpeg

### ISSUE THREAD

**Issue by kpind-aarhus** [aarhusstadsarkiv/misc-tools#1]
Hej Kristian, 

Har du mulighed for at konvertere denne pdf til separate jpeg-filer: https://we.tl/t-W8Xuxq4fUB

. Af en eller anden grund har jeg kun pdf’en og ikke billedfilerne. 

Filen er for stor til de gratis-værktøjer, jeg kan finde på nettet..

**Comment by jnik-aarhus** [comment]
File is available on slack (wetransfer link is broken)

**Comment by jnik-aarhus** [comment]
This probably not trivial, unfortunately. Check out PyMuPDF.
